services:
    bitbag_sylius_cms_plugin.sitemap_provider.page:
      class: BitBag\SyliusCmsPlugin\Sitemap\Provider\PageUrlProvider
      arguments:
          - "@bitbag_sylius_cms_plugin.repository.page"
          - "@router"
          - "@sylius.sitemap_url_factory"
          - "@sylius.context.locale"
          - "@sylius.context.channel"
      tags:
          - "sylius.sitemap_provider"
